### ISSUE TITLE
Complete "Running the Test Suite" cookbook

### ISSUE THREAD

**Issue by mmoreram** [elcodi/docs#45]
Add "How to execute specific Behat tests with tags" in "Running the Test Suite" cookbook.
This information is already defined in Behat documentation, but in order to make easier for our users any specific test execution using tags, would be nice to add a small reference.

``` bash
php bin/behat --tags="store"
php bin/behat --tags="javascript"
```

**Comment by cordoval** [comment]
done @mmoreram
